// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWOwaqZXbrsOPgw0Oxa7dzku5uXPOvpe0',
    appId: '1:854577973221:web:a8a1acd4ae7ba44da1910c',
    messagingSenderId: '854577973221',
    projectId: 'my-notes-447',
    authDomain: 'my-notes-447.firebaseapp.com',
    storageBucket: 'my-notes-447.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl0tgpV_Rmk3NCh4ZHYLNYKGvlVQVbgEA',
    appId: '1:854577973221:android:dd0f14fa99313e4da1910c',
    messagingSenderId: '854577973221',
    projectId: 'my-notes-447',
    storageBucket: 'my-notes-447.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhdIY0cxKMXYZowMci-m9hHFT73fc4onw',
    appId: '1:854577973221:ios:a9830b683913ad39a1910c',
    messagingSenderId: '854577973221',
    projectId: 'my-notes-447',
    storageBucket: 'my-notes-447.appspot.com',
    iosClientId: '854577973221-4a4oleroc6jkide2lsa0obur11iso268.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhdIY0cxKMXYZowMci-m9hHFT73fc4onw',
    appId: '1:854577973221:ios:e34eb55ef7305c85a1910c',
    messagingSenderId: '854577973221',
    projectId: 'my-notes-447',
    storageBucket: 'my-notes-447.appspot.com',
    iosClientId: '854577973221-end0svf49q2hv7u6kdcejergq2cfjrs4.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp.RunnerTests',
  );
}
